FROM golang:1.14.4 AS builder

ENV GO111MODULE=on  CGO_ENABLED=0 GOOS=linux GOARCH=amd64

WORKDIR /app
COPY . .

RUN go build -a -ldflags "-linkmode external -extldflags '-static' -s -w" -o inception ./cmd/server/main.go

FROM scratch
WORKDIR /app
COPY --from=builder /app/inception .
COPY ./config ./config
CMD ["./inception"]

